apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: k8s-program
  labels: 
    app: user
spec:
  type: NodePort
  selector:
    app: user
  ports:
    - name: userport
      port: 8083
      targetPort: 8081
      nodePort: 30083
      protocol: TCP
