apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  {{- template "mychart.labels" }}
  namespace: {{ .Values.namespace.name }}
data:
  Postgres_DB: {{ .Values.userConfig.postgresDB | quote }}
  User_Management_Endpoint_Health_Group_Exploratory_Include: {{ .Values.userConfig.userManagementEndpointHealthGroupExploratoryInclude
    | quote }}
  User_Management_Endpoint_Health_Group_Exploratory_Show_Details: {{ .Values.userConfig.userManagementEndpointHealthGroupExploratoryShowDetails
    | quote }}
  User_Management_Endpoints_Web_Exposure_Include: {{ .Values.userConfig.userManagementEndpointsWebExposureInclude
    | quote }}
  User_Management_Health_LivenessState_Enabled: {{ .Values.userConfig.userManagementHealthLivenessStateEnabled
    | quote }}
  User_Management_Health_ReadinessState_Enabled: {{ .Values.userConfig.userManagementHealthReadinessStateEnabled
    | quote }}
  User_Management_Security_Enabled: {{ .Values.userConfig.userManagementSecurityEnabled
    | quote }}
  User_Management_endpoint_health_probes_enabled: {{ .Values.userConfig.userManagementEndpointHealthProbesEnabled
    | quote }}
  User_datasource_url: {{ .Values.userConfig.userDatasourceUrl | quote }}
  User_hibernate_ddlauto: {{ .Values.userConfig.userHibernateDdlauto | quote }}
  User_hibernate_dialect: {{ .Values.userConfig.userHibernateDialect | quote }}
  User_server_port: {{ .Values.userConfig.userServerPort | quote }}