apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{ .Values.namespace.name }}
  labels: 
    app: user
spec:
  type: {{ .Values.userService.type }}
  selector:
    app: user
  ports:
    {{- .Values.userService.ports | toYaml | nindent 2 -}}
