apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
  namespace: k8s-program
  labels:
    app: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user-app
        image: eds832/userapplication:2.0.0
        ports:
        - containerPort: 8081
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://user-db-service:5432/users
          - name: SPRING_DATASOURCE_USERNAME
            value: admin
          - name: SPRING_DATASOURCE_PASSWORD
            value: '1234'
          - name: SPRING_JPA_HIBERNATE_DDLAUTO
            value: create-drop
          - name: SERVER_PORT
            value: '8081'
          - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
            value: org.hibernate.dialect.PostgreSQLDialect
        volumeMounts:
          - mountPath: "/mnt/postgres"
            name: user-persitent-volume
      volumes:
        - name: user-persitent-volume
          persistentVolumeClaim:
            claimName: user-persistent-volume-claim
