apiVersion: v1
kind: PersistentVolume
metadata:
  name: post-persistent-volume
  namespace: k8s-program
  labels:
    type: local
spec:
  capacity: 
    storage: 1Gi
  storageClassName: manual
  hostPath:
    path: "/mnt/mysql"
  accessModes:
    - ReadWriteMany
