apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: post-persistent-volume-claim
  namespace: k8s-program
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
