apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-program
  name: user-db
  labels:
    database: user
spec:
  replicas: 1
  selector:
    matchLabels:
      database: user
  template:
    metadata:
      labels:
        database: user
    spec:
      containers:
      - name: user-db
        image: postgres:15.2
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: admin
          - name: POSTGRES_PASSWORD
            value: '1234'
          - name: POSTGRES_DB
            value: users
