apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: k8s-program
  labels: 
    app: post
spec:
  type: NodePort
  selector:
    app: post
  ports:
    - name: postport
      port: 8084
      targetPort: 8082
      nodePort: 30084
      protocol: TCP
