apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: post-statefulset-database
  namespace: k8s-program
  labels:
    database: post-statefulset
spec:
  selector:
    matchLabels:
      database: post-statefulset
  serviceName: post-statefulset-database
  replicas: 1
  template:
    metadata:
      labels:
        database: post-statefulset
    spec:
      containers:
      - name: post-statefulset-database
        image: mysql:5.7
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: post-secret
                key: Post_DB_Root_Password
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: post-config
                key: Mysql_DB
        volumeMounts:
          - mountPath: "/mnt/mysql"
            name: post-statefulset-claim
          - name: init-post-db-script
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-post-db-script
          configMap:
            name: init-post-db
  volumeClaimTemplates:
    - metadata:
        name: post-statefulset-claim
      spec:
        accessModes: [ "ReadWriteMany" ]
        storageClassName: "hostpath"
        resources:
          requests:
            storage: 1Gi