apiVersion: v1
kind: ConfigMap
metadata:
  name: init-post-db 
  namespace: k8s-program
data:
  init_post_db.sql: |
    CREATE TABLE posts (user_id BIGINT NOT NULL PRIMARY KEY,author_id BIGINT NOT NULL,text VARCHAR(100) NOT NULL,posted_at DATE NOT NULL);
