apiVersion: v1
kind: Service
metadata:
  name: post-service-loadbalancer
  namespace: k8s-program
  labels: 
    app: post
spec:
  type: LoadBalancer
  selector:
    app: post
  ports:
    - port: 8084
      targetPort: 8082
