apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-statefulset-database
  namespace: k8s-program
  labels:
    database: user-statefulset
spec:
  selector:
    matchLabels:
      database: user-statefulset
  serviceName: user-statefulset-database
  replicas: 1
  template:
    metadata:
      labels:
        database: user-statefulset
    spec:
      containers:
      - name: user-statefulset-database
        image: postgres:15.2
        ports:
          - containerPort: 5432
        startupProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: user-secret
                key: Postgres_User
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: user-secret
                key: Postgres_Password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: user-config
                key: Postgres_DB
        volumeMounts:
          - mountPath: /mnt/postgres
            name: user-statefulset-claim
          - mountPath: /docker-entrypoint-initdb.d
            name: init-user-db-script
      volumes: 
         - name: init-user-db-script
           configMap:
             name: init-user-db
             defaultMode: 420
             items:
             - key: init_user_db
               path: init_user_db.sql       
  volumeClaimTemplates:
    - metadata:
        name: user-statefulset-claim
      spec:
        accessModes: [ "ReadWriteMany" ]
        storageClassName: "hostpath"
        resources:
          requests:
            storage: 1Gi