apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: k8s-program
data:
  User_datasource_url: "jdbc:postgresql://user-statefulset-db-service:5433/users"
  Postgres_DB: "users"
  User_hibernate_ddlauto: "create-drop"
  User_server_port: "8081"
  User_hibernate_dialect: "org.hibernate.dialect.PostgreSQLDialect"