apiVersion: v1
kind: Secret
metadata:
  name: post-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
  Post_DB_Root_Password: {{ required "postSecret.postDBRootPassword is required"
    .Values.postSecret.postDBRootPassword | b64enc | quote }}
  Mysql_User: {{ required "postSecret.mysqlUser is required" .Values.postSecret.mysqlUser
    | b64enc | quote }}