apiVersion: v1
kind: Secret
metadata:
  name: user-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
data: 
  Postgres_User: {{ required "userSecret.postgresUser is required" .Values.userSecret.postgresUser
    | b64enc | quote }}
  Postgres_Password: {{ required "userSecret.postgresPassword is required" .Values.userSecret.postgresPassword
    | b64enc | quote }}