apiVersion: v1
kind: Service
metadata:
  name: post-statefulset-db-service
  namespace: k8s-program
  labels:
    database: post-statefulset
spec:
  type: ClusterIP
  selector:
    database: post-statefulset
  ports:
    - port: 3307
      targetPort: 3306