apiVersion: v1
kind: Service
metadata:
  name: user-statefulset-db-service
  namespace: k8s-program
  labels:
    database: user-statefulset
spec:
  type: ClusterIP
  selector:
    database: user-statefulset
  ports:
    - port: 5433
      targetPort: 5432
