apiVersion: v1
kind: ConfigMap
metadata:
  name: init-user-db 
  namespace: k8s-program
data:
  init_user_db: |
    CREATE TABLE users (user_id BIGINT NOT NULL PRIMARY KEY,username VARCHAR(20) NOT NULL,amount_of_posts BIGINT DEFAULT 0);