apiVersion: v1
kind: ConfigMap
metadata:
  name: post-config
  namespace: k8s-program
data:
  Post_datasource_url: "jdbc:mysql://post-statefulset-db-service:3307/posts?useSSL=false"
  Mysql_DB: "posts"
  Post_hibernate_ddlauto: "create-drop"
  Post_server_port: "8082"
  Post_hibernate_dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
  User_App_URL: "http://user-service:8083/users/"
  Post_Management_Endpoints_Web_Exposure_Include: "*"
  Post_Management_endpoint_health_probes_enabled: "true"
  Post_Management_Health_LivenessState_Enabled: "true"
  Post_Management_Health_ReadinessState_Enabled: "true"
  Post_Management_Endpoint_Health_Group_Exploratory_Include: "livenessState,readinessState,ping"
  Post_Management_Endpoint_Health_Group_Exploratory_Show_Details: "always"
  Post_Management_Security_Enabled: "false"