apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-app
  namespace: k8s-program
  labels:
    app: post
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
      - name: post-app
        image: eds832/postapplication:2.0.0
        ports:
        - containerPort: 8082
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://post-db-service:3306/posts?useSSL=false
          - name: SPRING_DATASOURCE_USERNAME
            value: root
          - name: SPRING_DATASOURCE_PASSWORD
            value: '1234'
          - name: USER_APP_URL
            value: http://user-service:8083/users/
          - name: SPRING_JPA_HIBERNATE_DDLAUTO
            value: create-drop
          - name: SERVER_PORT
            value: '8082'
          - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
            value: org.hibernate.dialect.MySQL5InnoDBDialect
        volumeMounts:
        - mountPath: "/mnt/mysql"
          name: post-persitent-volume
      volumes:
      - name: post-persitent-volume
        persistentVolumeClaim:
          claimName: post-persistent-volume-claim
